root: true
env:
  es6: true
  node: true
extends: 'eslint:recommended'
parser: babel-eslint
rules:
  eol-last:
    - error
    - always
  indent:
    - error
    - 4
    - SwitchCase: 1
      ignoredNodes:
      - TemplateLiteral
  linebreak-style:
    - error
    - unix
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
  require-await:
    - warn
  require-atomic-updates:
    - off
  semi:
    - error
    - always
